# Generated by Django 5.0.6 on 2024-06-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorreg',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
